### ISSUE TITLE
492. Transaction->loading list(WB ticket number and Delivery Date)

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#21]
weight ticket no. - need 2nd time input to enable

**Comment by edward123** [comment]
reopen

**Comment by Mamta123** [comment]
Please describe in detail

**Comment by edward123** [comment]
like the one highlighted, actuall before saving, we have already keyed in WB ticket number, but after saving, this column is showing zero only. Need to re enter WB ticket number so that it can be saved. 
![image](https://f.cloud.github.com/assets/4178426/802979/dab9899e-eddf-11e2-9bbc-41d5c6225de0.png)

**Comment by edward123** [comment]
same problem for DeliveryDate, before saving, we have changed Delivery Date to 15/7, but after saving, the Delivery Date is still showing 13/7. Need to re enter 15/7 as Delivery Date so that it can be saved. 
![image](https://f.cloud.github.com/assets/4178426/803004/be3360aa-ede0-11e2-9888-5b17cfad7bdd.png)

**Comment by edward123** [comment]
supposed preliminary delivery date for above order was 13th July, so at that time when we created loading list, we input 13th July. But actually, customer came to pick up FG on 16th July. Therefore, we have to change delivery date as 16th July. But in CuBe, the first time to save 16th as delivery date is unsuccessful to show in LL screen, still showing 13th as delivery date; need to edit again and change to 16th so that it can be showing as 16th in LL screen.

**Comment by edward123** [comment]
when input pure digit such as 112, WB ticket no.,  it is able to show correct data in this column at the first time, but when input actual WB ticket no. such as W13100666, first time it is showing 0, need to input 2nd time, then it can show the correct WB ticket no.. Pls note it. Problem may be the character like W. 
![image](https://f.cloud.github.com/assets/4178426/1340657/1aeb9d8c-3637-11e3-805e-65bbfa99ff70.png)

**Comment by edward123** [comment]
Date Time Stamp : 10/23/2013 6:09:19 PM
Source of error :    在 System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   在 System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   在 CuBe.t_tool.updatequery(String strupdate) 位置 D:\ApCuBeVSS\CuBe_NSX_26Sept\CuBe_v2.0.root\CuBe_v2.0\CuBe\t_tool.vb:行号 71
   在 CuBe.frmAddLoadingList.cmdSave_Click(Object sender, EventArgs e) 位置 D:\ApCuBeVSS\CuBe_NSX_26Sept\CuBe_v2.0.root\CuBe_v2.0\CuBe\frmAddLoadingList.vb:行号 760
Error Details : Invalid column name 'W12345678'.

**Comment by edward123** [comment]
closed
