### ISSUE TITLE
Cancel freezed plan

### ISSUE THREAD

**Issue by Mamta123** [cubensx/cube#4]
freezed plan shall be able to cancel before creating loading list, since user might freeze the plan wrongly by accident.

**Comment by hemantbansal** [comment]
[15-05-2013 19:10:01]
Hemant : In Cancel Order after freezing , if we give u the facility to unfreeze any freeze plan then will it solve ur purpose, because as soon as ur freeze plan will be unfreeze, then all order which are freeze in that plan will be in created status and u can modify, cancel those orders
Edward Hong: ya, i think it would be good to unfreeze any freeze plan

**Comment by hemantbansal** [comment]
[15-05-2013 19:12:01]
Hemant : Edward in this case also many scenario will arise that we need to finalize as following
1. we wont be able to update machine available time as it was before freezing that plan , because we don't have history
2. We wont we able to revert back offcut stock status which was before freezing that plan because we may not have history, that u have to do it manually , but whichever stock was blocked for that plan we can release that
3. If suppose any plan have 2 orders and one order of that plan has delivered and other is cancel , then what system will do , because if we unfreeze that plan it means both order will be in created status and one order has delivered already
4. If Plan is uploaded then it will be difficult to unfreeze the plan, even there is no meaning of unfreezing plan , because production is already done, if order is cancel and if we have FG material of that order then it is only scrap for us

**Comment by edward123** [comment]
this time we wanna cancel freezed plan is not because customer would cancel the order after producttion, but because example we wanna run 2 orders in same plan, which have same grade and diameter, so that we can optimize the plan. But by accident, we freeze one of the plans only. Therefore, we have to copy another order and then cancel the freezed plan. So the offcut stock shall be able to revert back. And given this scenario, above comment from Hemant can be not taken into account.

**Comment by edward123** [comment]
Hemant, i'm testing cancel freezed plan
[4:32:16 PM] Edward Hong: got following problem, plan has error
[4:32:21 PM] **\* Edward Hong 发送 IMG_10092013_163221.png ***
![image](https://f.cloud.github.com/assets/4178426/1113171/330ed018-19f5-11e3-8e5e-808543a195d4.png)

[4:33:32 PM] Edward Hong: i have tried manual assignment, but still have such error
[4:33:58 PM] Edward Hong: meaning still cannot work
[4:34:19 PM] Edward Hong: meanwhile, we have enough stock to cover this plan
[4:37:39 PM] Edward Hong: pls note FXDSM1309CA04 and  FXDSM1309CA05 are same order, the latter one i copied from former one
[4:37:46 PM] Edward Hong: all have the same error
[4:37:48 PM | 以删除 4:37:59 PM] Edward Hong: 此消息已被删除
[4:38:16 PM] **\* Edward Hong 发送 IMG_10092013_163816.png ***
![image](https://f.cloud.github.com/assets/4178426/1113174/3af14cf2-19f5-11e3-9a3f-edd2671ba64b.png)
